ALTER TABLE "ProductShade" ADD COLUMN IF NOT EXISTS "price" INTEGER;
ALTER TABLE "ProductShade" ADD COLUMN IF NOT EXISTS "originalPrice" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProductShade" ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProductShade" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0;
