-- Home page builder: new block types + banner link fields
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'BANNER_FULL';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'BANNER_GRID_2';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'BANNER_GRID_3';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'BANNER_CAROUSEL';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'CATEGORY_TILES';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'MAKEUP_CATEGORIES';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'BRAND_SHOWCASE';

ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "linkType" TEXT;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "linkValue" TEXT;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "discountText" TEXT;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT;
