/** Minimal JSON Schema — GPT returns product-line names only (no description/category/shades). */
export const MINIMAL_PRODUCT_NAME_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    representative_barcode: { type: "string" },
    product_name_ar: { type: "string" },
    product_name_en: { type: "string" },
    confidence: { type: "number" },
    needs_review: { type: "boolean" },
    review_notes: { type: ["string", "null"] },
    source_url: { type: "string" },
  },
  required: [
    "representative_barcode",
    "product_name_ar",
    "product_name_en",
    "confidence",
    "needs_review",
    "review_notes",
    "source_url",
  ],
} as const;

/** Legacy full schema — kept for reading old cache entries only. */
export const PRODUCT_RESEARCH_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    barcode: { type: "string" },
    brand_ar: { type: "string" },
    brand_en: { type: "string" },
    product_name_ar: { type: "string" },
    product_name_en: { type: "string" },
    size_value: { type: ["number", "null"] },
    size_unit_ar: { type: "string" },
    size_unit_en: { type: "string" },
    product_type_ar: { type: "string" },
    product_type_en: { type: "string" },
    description_ar: { type: "string" },
    description_en: { type: "string" },
    usage_instructions_ar: { type: "string" },
    usage_instructions_en: { type: "string" },
    main_category: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string" },
        name_ar: { type: "string" },
        name_en: { type: "string" },
      },
      required: ["id", "name_ar", "name_en"],
    },
    subcategories: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          name_ar: { type: "string" },
          name_en: { type: "string" },
        },
        required: ["id", "name_ar", "name_en"],
      },
    },
    secondary_categories: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          name_ar: { type: "string" },
          name_en: { type: "string" },
        },
        required: ["id", "name_ar", "name_en"],
      },
    },
    source_urls: {
      type: "array",
      items: { type: "string" },
    },
    confidence: { type: "number" },
    needs_review: { type: "boolean" },
    review_notes: { type: ["string", "null"] },
  },
  required: [
    "barcode",
    "brand_ar",
    "brand_en",
    "product_name_ar",
    "product_name_en",
    "size_value",
    "size_unit_ar",
    "size_unit_en",
    "product_type_ar",
    "product_type_en",
    "description_ar",
    "description_en",
    "usage_instructions_ar",
    "usage_instructions_en",
    "main_category",
    "subcategories",
    "secondary_categories",
    "source_urls",
    "confidence",
    "needs_review",
    "review_notes",
  ],
} as const;
