-- HomeBlockType: CIRCLE_TILES, ROUTINE_CAROUSEL, CARE_HUB
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'CIRCLE_TILES';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'ROUTINE_CAROUSEL';
ALTER TYPE "HomeBlockType" ADD VALUE IF NOT EXISTS 'CARE_HUB';

-- SkinConcern image
ALTER TABLE "SkinConcern" ADD COLUMN IF NOT EXISTS "imageId" TEXT;
ALTER TABLE "SkinConcern" DROP CONSTRAINT IF EXISTS "SkinConcern_imageId_fkey";
ALTER TABLE "SkinConcern" ADD CONSTRAINT "SkinConcern_imageId_fkey" FOREIGN KEY ("imageId") REFERENCES "Media"("id") ON DELETE SET NULL ON UPDATE CASCADE;
